"""change col names

Revision ID: 0663c2047c25
Revises: 4da599eb0cca
Create Date: 2022-05-14 00:51:38.377930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0663c2047c25'
down_revision = '4da599eb0cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_column('companies', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'last_updated')
    # ### end Alembic commands ###
