"""empty message

Revision ID: 09c6cf9aea1d
Revises: 640867662b52
Create Date: 2022-05-21 18:22:02.653105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c6cf9aea1d'
down_revision = '640867662b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('do_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'do_datetime')
    # ### end Alembic commands ###
