"""empty message

Revision ID: 0afba3732efe
Revises: 
Create Date: 2022-06-04 23:52:44.823097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0afba3732efe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=False),
    sa.Column('company_website_url', sa.String(length=255), nullable=False),
    sa.Column('company_general_email', sa.String(length=120), nullable=False),
    sa.Column('company_booking_email', sa.String(length=120), nullable=False),
    sa.Column('company_phone', sa.String(length=120), nullable=False),
    sa.Column('stripe_account', sa.String(length=255), nullable=True),
    sa.Column('enabled_auto_invoice', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('is_driver', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=90), nullable=False),
    sa.Column('last_name', sa.String(length=90), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('DL_number', sa.String(length=255), nullable=True),
    sa.Column('DL_state', sa.String(length=2), nullable=True),
    sa.Column('DL_expr', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pax_capacity', sa.Integer(), nullable=False),
    sa.Column('license_plate_number', sa.String(length=12), nullable=False),
    sa.Column('exterior_color', sa.String(length=120), nullable=True),
    sa.Column('vin_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_air_conditioning', sa.Boolean(), nullable=True),
    sa.Column('has_dance_pole', sa.Boolean(), nullable=True),
    sa.Column('has_luggage_space', sa.Boolean(), nullable=True),
    sa.Column('has_tables', sa.Boolean(), nullable=True),
    sa.Column('has_onboard_bathroom', sa.Boolean(), nullable=True),
    sa.Column('has_onboard_bar', sa.Boolean(), nullable=True),
    sa.Column('has_refrigerator', sa.Boolean(), nullable=True),
    sa.Column('has_trash_can', sa.Boolean(), nullable=True),
    sa.Column('has_ice_chest', sa.Boolean(), nullable=True),
    sa.Column('has_wheelchair_accessibility', sa.Boolean(), nullable=True),
    sa.Column('has_aux', sa.Boolean(), nullable=True),
    sa.Column('has_bluetooth', sa.Boolean(), nullable=True),
    sa.Column('has_dvd_player', sa.Boolean(), nullable=True),
    sa.Column('has_karaoke', sa.Boolean(), nullable=True),
    sa.Column('has_usb', sa.Boolean(), nullable=True),
    sa.Column('has_power_outlets', sa.Boolean(), nullable=True),
    sa.Column('has_wifi', sa.Boolean(), nullable=True),
    sa.Column('has_tv', sa.Boolean(), nullable=True),
    sa.Column('has_gaming_console', sa.Boolean(), nullable=True),
    sa.Column('is_alcohol_allowed', sa.Boolean(), nullable=True),
    sa.Column('is_smoking_allowed', sa.Boolean(), nullable=True),
    sa.Column('is_pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('is_food_allowed', sa.Boolean(), nullable=True),
    sa.Column('is_children_allowed', sa.Boolean(), nullable=True),
    sa.Column('min_total_base_rate', sa.Integer(), nullable=True),
    sa.Column('deadhead_rate_per_mile', sa.Integer(), nullable=True),
    sa.Column('trip_rate_per_mile', sa.Integer(), nullable=True),
    sa.Column('weekend_hourly_rate', sa.Integer(), nullable=True),
    sa.Column('weekend_hourly_min', sa.Integer(), nullable=True),
    sa.Column('weekday_hourly_rate', sa.Integer(), nullable=True),
    sa.Column('weekday_hourly_min', sa.Integer(), nullable=True),
    sa.Column('total_deadhead_duration', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=90), nullable=False),
    sa.Column('last_name', sa.String(length=90), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('contacts_company_id', sa.Integer(), nullable=True),
    sa.Column('home_address', sa.String(length=255), nullable=True),
    sa.Column('work_address', sa.String(length=255), nullable=True),
    sa.Column('work_position', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contacts_company_id'], ['contacts_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.Column('is_driver', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=90), nullable=False),
    sa.Column('last_name', sa.String(length=90), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('DL_number', sa.String(length=255), nullable=True),
    sa.Column('DL_state', sa.String(length=2), nullable=True),
    sa.Column('DL_expr', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_accepted', sa.Boolean(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('driver_user_id', sa.Integer(), nullable=True),
    sa.Column('contacts_customer_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('pu_datetime', sa.DateTime(), nullable=False),
    sa.Column('pu_address', sa.String(length=255), nullable=True),
    sa.Column('pu_is_flight', sa.Boolean(), nullable=True),
    sa.Column('pu_arrival_airport', sa.String(length=255), nullable=True),
    sa.Column('pu_flight_code', sa.String(length=6), nullable=True),
    sa.Column('pu_airline', sa.String(length=255), nullable=True),
    sa.Column('do_datetime', sa.DateTime(), nullable=True),
    sa.Column('do_address', sa.String(length=255), nullable=True),
    sa.Column('do_is_flight', sa.Boolean(), nullable=True),
    sa.Column('do_departure_airport', sa.String(length=255), nullable=True),
    sa.Column('do_flight_code', sa.String(length=6), nullable=True),
    sa.Column('do_airline', sa.String(length=255), nullable=True),
    sa.Column('pu_pax', sa.Integer(), nullable=False),
    sa.Column('do_pax', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('driver_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('price_gratituity', sa.Float(), nullable=True),
    sa.Column('price_tax', sa.Float(), nullable=True),
    sa.Column('price_tolls', sa.Float(), nullable=True),
    sa.Column('price_discount', sa.Float(), nullable=True),
    sa.Column('price_other1', sa.Float(), nullable=True),
    sa.Column('price_other2', sa.Float(), nullable=True),
    sa.Column('price_other3', sa.Float(), nullable=True),
    sa.Column('price_other4', sa.Float(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('stops', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contacts_customer_id'], ['contacts_customers.id'], ),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('contacts_customer_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('due_on', sa.DateTime(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contacts_customer_id'], ['contacts_customers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('trips')
    op.drop_table('user_invites')
    op.drop_table('contacts_customers')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('contacts_companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
