"""empty message

Revision ID: 0c8b9e76c092
Revises: 2e41700afec0
Create Date: 2022-05-25 18:57:50.773979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8b9e76c092'
down_revision = '2e41700afec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts_customers', 'full_name',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts_customers', 'full_name',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    # ### end Alembic commands ###
