"""empty message

Revision ID: 2e41700afec0
Revises: 
Create Date: 2022-05-25 18:57:18.694611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e41700afec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_customers', sa.Column('full_name', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts_customers', 'full_name')
    # ### end Alembic commands ###
