"""Add vehicle-company relationship

Revision ID: 351e0767ad12
Revises: aa8f8cf9f29c
Create Date: 2022-05-11 22:40:32.674542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351e0767ad12'
down_revision = 'aa8f8cf9f29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vehicles', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'company_id')
    # ### end Alembic commands ###
