"""empty message

Revision ID: 4593e3e3636f
Revises: ade08c8bfbed
Create Date: 2022-05-25 00:18:12.754380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4593e3e3636f'
down_revision = 'ade08c8bfbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('enabled_auto_invoice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'enabled_auto_invoice')
    # ### end Alembic commands ###
