"""empty message

Revision ID: 4ab2589c4bc8
Revises: c876a87560fe
Create Date: 2022-05-22 21:33:15.982709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ab2589c4bc8'
down_revision = 'c876a87560fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('stops', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'stops')
    # ### end Alembic commands ###
