"""change col names

Revision ID: 4da599eb0cca
Revises: 2ed3b2c3aa42
Create Date: 2022-05-14 00:50:41.223382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4da599eb0cca'
down_revision = '2ed3b2c3aa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('companies', 'last_updated')
    op.drop_column('companies', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
