"""empty message

Revision ID: 4e70a26b7ec4
Revises: 7a87895b50a8
Create Date: 2022-05-24 20:14:42.517127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e70a26b7ec4'
down_revision = '7a87895b50a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount_due', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'amount_due')
    # ### end Alembic commands ###
