"""empty message

Revision ID: 5df817e4a722
Revises: 0afba3732efe
Create Date: 2022-06-05 13:49:12.283673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df817e4a722'
down_revision = '0afba3732efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_customers_email_key', 'contacts_customers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_customers_email_key', 'contacts_customers', ['email'])
    # ### end Alembic commands ###
