"""add trips

Revision ID: 640867662b52
Revises: e36bbf947f8d
Create Date: 2022-05-21 18:04:36.764135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640867662b52'
down_revision = 'e36bbf947f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacts_customer_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('pu_datetime', sa.DateTime(), nullable=False),
    sa.Column('pu_address', sa.String(length=255), nullable=True),
    sa.Column('pu_is_flight', sa.Boolean(), nullable=True),
    sa.Column('pu_arrival_airport', sa.String(length=255), nullable=True),
    sa.Column('pu_flight_code', sa.String(length=6), nullable=True),
    sa.Column('pu_airline', sa.String(length=255), nullable=True),
    sa.Column('do_address', sa.String(length=255), nullable=True),
    sa.Column('do_is_flight', sa.Boolean(), nullable=True),
    sa.Column('do_departure_airport', sa.String(length=255), nullable=True),
    sa.Column('do_flight_code', sa.String(length=6), nullable=True),
    sa.Column('do_airline', sa.String(length=255), nullable=True),
    sa.Column('pu_pax', sa.Integer(), nullable=False),
    sa.Column('do_pax', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('driver_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('price_gratituity', sa.Float(), nullable=True),
    sa.Column('price_tax', sa.Float(), nullable=True),
    sa.Column('price_tolls', sa.Float(), nullable=True),
    sa.Column('price_discount', sa.Float(), nullable=True),
    sa.Column('price_other1', sa.Float(), nullable=True),
    sa.Column('price_other2', sa.Float(), nullable=True),
    sa.Column('price_other3', sa.Float(), nullable=True),
    sa.Column('price_other4', sa.Float(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('has_stops', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contacts_customer_id'], ['contacts_customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
