"""empty message

Revision ID: 6d2063c4aa2d
Revises: 9a4cbb0d904d
Create Date: 2022-07-21 15:31:57.999784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d2063c4aa2d'
down_revision = '9a4cbb0d904d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('driver_user_id', sa.Integer(), nullable=True),
    sa.Column('contacts_customer_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('pu_datetime', sa.DateTime(), nullable=False),
    sa.Column('pu_address', sa.String(length=255), nullable=True),
    sa.Column('pu_is_flight', sa.Boolean(), nullable=True),
    sa.Column('pu_arrival_airport', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pu_flight_code', sa.String(length=6), nullable=True),
    sa.Column('pu_airline', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('do_datetime', sa.DateTime(), nullable=True),
    sa.Column('do_address', sa.String(length=255), nullable=True),
    sa.Column('do_is_flight', sa.Boolean(), nullable=True),
    sa.Column('do_departure_airport', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('do_flight_code', sa.String(length=6), nullable=True),
    sa.Column('do_airline', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pu_pax', sa.Integer(), nullable=False),
    sa.Column('do_pax', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('driver_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('price_gratituity', sa.Float(), nullable=True),
    sa.Column('price_tax', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('price_tolls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('price_discount', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('price_other1', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('price_other2', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('price_other3', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('price_other4', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('stops', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contacts_customer_id'], ['contacts_customers.id'], ),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_foreign_key(None, 'invoices', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_table('trips')
    # ### end Alembic commands ###
