"""empty message

Revision ID: 7017d8708e25
Revises: 93fffa497731
Create Date: 2022-06-17 23:18:31.620196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7017d8708e25'
down_revision = '93fffa497731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('photo1', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('photo2', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('photo3', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'photo3')
    op.drop_column('vehicles', 'photo2')
    op.drop_column('vehicles', 'photo1')
    # ### end Alembic commands ###
