"""empty message

Revision ID: 787f2df67866
Revises: 0ec007fb362c
Create Date: 2022-08-09 21:34:39.534090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787f2df67866'
down_revision = '0ec007fb362c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('parenttrip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trips', 'trips', ['parenttrip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'parenttrip_id')
    # ### end Alembic commands ###
