"""add uuids

Revision ID: 81af96b275e5
Revises: bd285fa3cb88
Create Date: 2022-06-07 13:37:27.909182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81af96b275e5'
down_revision = 'bd285fa3cb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['uuid'])
    op.create_unique_constraint(None, 'contacts_companies', ['uuid'])
    op.create_unique_constraint(None, 'contacts_customers', ['uuid'])
    op.create_unique_constraint(None, 'invoices', ['uuid'])
    op.create_unique_constraint(None, 'trips', ['uuid'])
    op.create_unique_constraint(None, 'user_invites', ['uuid'])
    op.create_unique_constraint(None, 'users', ['uuid'])
    op.create_unique_constraint(None, 'vehicles', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_invites', type_='unique')
    op.drop_constraint(None, 'trips', type_='unique')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_constraint(None, 'contacts_customers', type_='unique')
    op.drop_constraint(None, 'contacts_companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
