"""empty message

Revision ID: 925fbdff712e
Revises: a63e2204c85c
Create Date: 2022-07-29 14:25:49.324159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '925fbdff712e'
down_revision = 'a63e2204c85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('passenger', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'passenger')
    # ### end Alembic commands ###
