"""empty message

Revision ID: 93fffa497731
Revises: 0074ef159ea8
Create Date: 2022-06-16 17:52:36.321614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93fffa497731'
down_revision = '0074ef159ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_type', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.alter_column('vehicles', 'license_plate_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_column('vehicles', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('type', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('vehicles', 'license_plate_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.drop_column('vehicles', 'vehicle_type')
    # ### end Alembic commands ###
