"""empty message

Revision ID: 9d030fbac86c
Revises: e871f7ed4499
Create Date: 2022-07-21 16:38:42.824011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d030fbac86c'
down_revision = 'e871f7ed4499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('price_discounts', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('trips', 'price_discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('price_discount', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('trips', 'price_discounts')
    # ### end Alembic commands ###
