"""empty message

Revision ID: a4193c676b33
Revises: b2ee05be55a4
Create Date: 2022-08-03 22:52:08.370252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4193c676b33'
down_revision = 'b2ee05be55a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('returntrip_id', sa.Integer(), nullable=True))
    op.alter_column('trips', 'trip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_foreign_key(None, 'trips', 'trips', ['returntrip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.alter_column('trips', 'trip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('trips', 'returntrip_id')
    # ### end Alembic commands ###
