"""empty message

Revision ID: a63e2204c85c
Revises: 
Create Date: 2022-07-28 20:25:30.542944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63e2204c85c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('setting_enabled_auto_invoice', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('setting_timezone', sa.String(length=255), nullable=True))
    op.drop_column('companies', 'enabled_auto_invoice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('enabled_auto_invoice', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'setting_timezone')
    op.drop_column('companies', 'setting_enabled_auto_invoice')
    # ### end Alembic commands ###
