"""empty message

Revision ID: ade08c8bfbed
Revises: eb2247c92c74
Create Date: 2022-05-24 23:59:22.642910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade08c8bfbed'
down_revision = 'eb2247c92c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('stripe_account', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'stripe_account')
    # ### end Alembic commands ###
