"""empty message

Revision ID: b2ee05be55a4
Revises: 0d87297778e1
Create Date: 2022-08-02 21:29:17.672590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ee05be55a4'
down_revision = '0d87297778e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('trip_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'trip_code')
    # ### end Alembic commands ###
