"""add uuids

Revision ID: bd285fa3cb88
Revises: 5df817e4a722
Create Date: 2022-06-07 13:36:04.907831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd285fa3cb88'
down_revision = '5df817e4a722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('contacts_companies', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('contacts_customers', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('trips', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('user_invites', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('vehicles', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'uuid')
    op.drop_column('users', 'uuid')
    op.drop_column('user_invites', 'uuid')
    op.drop_column('trips', 'uuid')
    op.drop_column('contacts_customers', 'uuid')
    op.drop_column('contacts_companies', 'uuid')
    op.drop_column('companies', 'uuid')
    # ### end Alembic commands ###
