"""empty message

Revision ID: c02d5d6a3b3c
Revises: 81af96b275e5
Create Date: 2022-06-14 23:17:54.722389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02d5d6a3b3c'
down_revision = '81af96b275e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('type', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'type')
    # ### end Alembic commands ###
