"""empty message

Revision ID: c47ee815270f
Revises: ff9ec13349fe
Create Date: 2022-05-18 23:41:32.048556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47ee815270f'
down_revision = 'ff9ec13349fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_customers', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts_customers', 'is_favorite')
    # ### end Alembic commands ###
