"""empty message

Revision ID: c876a87560fe
Revises: 
Create Date: 2022-05-22 16:19:08.789779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c876a87560fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('driver_user_id', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'trips', 'users', ['driver_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'is_active')
    op.drop_column('trips', 'driver_user_id')
    # ### end Alembic commands ###
