"""empty message

Revision ID: e36bbf947f8d
Revises: ed91fbd0b2b1
Create Date: 2022-05-19 14:29:45.007887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36bbf947f8d'
down_revision = 'ed91fbd0b2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_companies', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contacts_companies', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts_companies', type_='foreignkey')
    op.drop_column('contacts_companies', 'company_id')
    # ### end Alembic commands ###
