"""empty message

Revision ID: e871f7ed4499
Revises: 6d2063c4aa2d
Create Date: 2022-07-21 16:37:58.396774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e871f7ed4499'
down_revision = '6d2063c4aa2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('price_gratuity', sa.Float(), nullable=True))
    op.drop_column('trips', 'price_gratituity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('price_gratituity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('trips', 'price_gratuity')
    # ### end Alembic commands ###
