"""empty message

Revision ID: eb2247c92c74
Revises: 4e70a26b7ec4
Create Date: 2022-05-24 20:23:57.343266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb2247c92c74'
down_revision = '4e70a26b7ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'uuid')
    # ### end Alembic commands ###
