"""add is_active field

Revision ID: ed91fbd0b2b1
Revises: c47ee815270f
Create Date: 2022-05-19 14:19:10.557545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed91fbd0b2b1'
down_revision = 'c47ee815270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_companies', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('contacts_customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts_customers', 'is_active')
    op.drop_column('contacts_companies', 'is_active')
    # ### end Alembic commands ###
