"""Add drivers

Revision ID: f9cd6364719b
Revises: 351e0767ad12
Create Date: 2022-05-11 23:22:27.179977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cd6364719b'
down_revision = '351e0767ad12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_users', sa.Column('creation_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operator_users', 'creation_code')
    # ### end Alembic commands ###
